### ISSUE TITLE
Homebrew not working correctly mojave

### ISSUE THREAD

**Issue by TheNite** [route1337/jamf-macos-scripts#8]
Hi,

using installhomebrew.sh to install homebrew through DEP on mojave is currently not working correctly,  get the following error:
`

xcode-select: error: invalid developer directory '/Library/Developer/CommandLineTools'==> This script will install:/usr/local/bin/brew/usr/local/share/doc/homebrew/usr/local/share/man/man1/brew.1/usr/local/share/zsh/site-functions/_brew/usr/local/etc/bash_completion.d/brew/usr/local/Homebrew==> The Xcode Command Line Tools will be installed.==> Searching online for the Command Line Tools==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progresssudo: no tty present and no askpass program specifiedFailed during: /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress-bash: /usr/local/bin/brew: No such file or directory
--
Error running script: return code was 127.

`

This script those work flawless on Catalina

**Comment by ahrenstein** [comment]
Hello @TheNite,

Sorry I never got notified about this issue.

This might be fixed ,but with the move to Apple Silicon being near complete, it's getting harder to test older operating systems.

I just pushed new changes, so please let me know if it's working.
